### ISSUE TITLE
DLL load failed while importing _typeconv

### ISSUE THREAD

**Issue by nbanyan** [wvsharber/BeatMapSynthesizer#39]
Using anaconda 4.8.2 and python 3.8.2 on a new Windows 10 Pro version 1909 (build 18363.836) installation.
'pip install numba' reports numba (0.49.0) and its requirements are installed.

Here's the command prompt and result:

(BSMapSynth-env) D:\Downloads\Utilities\BeatMapSynthesizer-master>python beatmapsynth.py "Music/Ehrling---Sthlm-Sunset.mp3" "Sthlm Sunset" segmented_HMM
Traceback (most recent call last):
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed while importing _typeconv: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "beatmapsynth.py", line 4, in <module>
    import librosa
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "E:\anaconda3\envs\BSMapSynth-env\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed while importing _typeconv: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: E:\anaconda3\envs\BSMapSynth-env\python.exe

(BSMapSynth-env) D:\Downloads\Utilities\BeatMapSynthesizer-master>

**Comment by theace0296** [comment]
Usually that error comes from a mismatch between your Python version and the module version. But numba v0.49.0 and Python 3.8.2 should be compatible. I would try doing a `pip install numba==0.49.1` or modifying the "Windows_environment.yml" file to change the version of numba to 0.49.1. You could also try changing the Python verison Conda is using to 3.8.3 rather than 3.8.2. 

As a last-ditch alternative, I was able to run it outside of a Conda env using Python 3.8.3. Attached is my requirements.txt that I generated by doing `pip freeze > requirements.txt`
[requirements.txt](https://github.com/wvsharber/BeatMapSynthesizer/files/4696617/requirements.txt)

**Comment by nbanyan** [comment]
Updating the environment with numba 0.49.1 fixed it.
Thank you.
